apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  ports:
  - name: "5984"
    port: 5984
    targetPort: 5984
  selector:
    io.kompose.service: couchdb
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
      - image: couchdb
        name: couchdb
        ports:
        - containerPort: 5984
        resources: {}
      restartPolicy: Always
status: {}
