kind: Service
apiVersion: v1
metadata:
  name: urlshortner
spec:
  selector:
    app: urlshortner
    tier: backend
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: urlshortner
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: urlshortner
        tier: backend
        track: latest
    spec:
      restartPolicy: Always
      containers:
        - name: hello
          image: "georgethomas111/url"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
             httpGet:
               path: /status
               port: 8080
             initialDelaySeconds: 1
             periodSeconds: 5
